# Generated by Django 3.1.2 on 2020-10-14 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(decimal_places=14, help_text='Lattitude of sighting location', max_digits=18, max_length=100)),
                ('Y', models.DecimalField(decimal_places=14, help_text='Longitude of sighting location', max_digits=18, max_length=100)),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique ID of the squirrel sighted', max_length=100)),
                ('Shift', models.CharField(choices=[('pm', 'PM'), ('am', 'AM')], default='am', help_text='Shift of Sighting', max_length=15)),
                ('Date', models.DateField(help_text='Date of sighting')),
                ('Age', models.CharField(blank=True, choices=[('juvenile', 'Juvenile'), ('adult', 'Adult'), ('Other', 'Other')], default='Other', help_text='Age of Squirrel', max_length=15)),
                ('Primary_Fur_Color', models.CharField(blank=True, choices=[('black', 'Black'), ('cinnamon', 'Cinnamon'), ('gray', 'Gray'), ('other', 'Other')], default='other', help_text='Color of Squirrel', max_length=50)),
                ('Location', models.CharField(blank=True, choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location of Squirrel', max_length=50)),
                ('Specific_Location', models.TextField(blank=True)),
                ('Running', models.BooleanField(default=False, help_text='Wheter or not squirrel was running')),
                ('Chasing', models.BooleanField(default=False, help_text='Wheter or not squirrel was chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Wheter or not squirrel was climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Wheter or not squirrel was eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Wheter or not squirrel was foraging')),
                ('Other_Activities', models.TextField(blank=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Wheter or not squirrel was kuking')),
                ('Quaas', models.BooleanField(default=False, help_text='Wheter or not squirrel was quaasig')),
                ('Moans', models.BooleanField(default=False, help_text='Wheter or not squirrel was moaning')),
                ('Tail_flags', models.BooleanField(default=False, help_text='Wheter or not squirrel was flagging tail')),
                ('Tail_twitches', models.BooleanField(default=False, help_text='Wheter or not squirrel was twitching tail')),
                ('Approaches', models.BooleanField(default=False, help_text='Wheter or not squirrel was approaching')),
                ('Indifferent', models.BooleanField(default=False, help_text='Wheter or not squirrel was indifferent')),
                ('Runs_from', models.BooleanField(default=False, help_text='Wheter or not squirrel runs from observer')),
            ],
        ),
    ]
