# Generated by Django 3.1.2 on 2020-10-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(blank=True, choices=[('juvenile', 'Juvenile'), ('adult', 'Adult'), ('Other', 'Other')], default='Other', help_text='Age of Squirrel', max_length=50),
        ),
    ]
