# Generated by Django 3.1.2 on 2020-10-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(choices=[('juvenile', 'Juvenile'), ('adult', 'Adult'), ('Other', 'Other')], default='Other', help_text='Age of Squirrel', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was approaching'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was chasing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was climbing'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was eating'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was foraging'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was indifferent'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was kuking'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Location',
            field=models.CharField(choices=[('ground plane', 'Ground Plane'), ('above ground', 'Above Ground'), ('other', 'Other')], default='other', help_text='Location of Squirrel', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was moaning'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Primary_Fur_Color',
            field=models.CharField(choices=[('black', 'Black'), ('cinnamon', 'Cinnamon'), ('gray', 'Gray'), ('other', 'Other')], default='other', help_text='Color of Squirrel', max_length=50),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was quaasig'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was running'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Runs_from',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel runs from observer'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_flags',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was flagging tail'),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Tail_twitches',
            field=models.BooleanField(default=False, help_text='Whether or not squirrel was twitching tail'),
        ),
    ]
